---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-chakulatrust-regulator
  labels:
    app: chaincode-chakulatrust-regulator
spec:
  selector:
    matchLabels:
      app: chaincode-chakulatrust-regulator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-chakulatrust-regulator
    spec:
      containers:
        - image: mfadhiligitau/chakulatrust:1.0
          imagePullPolicy: Always
          name: chaincode-chakulatrust-regulator
          env:
            - name: CHAINCODE_ID
              value: "chakulatrust:24d7902a706c59f3f0754df151fd060096ef1f932baf1fe4bd9456b95114d265"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
