--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: chakulatrust-storage
  labels:
    app: chakulatrust-storage
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-chakulatrust-storage
