--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: producetrace-middleman
  labels:
    app: producetrace-middleman
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-producetrace-middleman
