--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: producetrace-storage
  labels:
    app: producetrace-storage
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-producetrace-storage
