apiVersion: batch/v1
kind: Job
metadata:
  name: create-certs
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: create-certs
          image: hyperledger/fabric-ca-tools:latest
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
          command:
            - /bin/sh
            - -c
            - |
              ./scripts/orderer-certs.sh &&
              ./scripts/farmer-certs.sh &&
              ./scripts/middleman-certs.sh &&
              ./scripts/processor-certs.sh &&
              ./scripts/distributor-certs.sh &&
              ./scripts/storage-certs.sh &&
              ./scripts/regulator-certs.sh &&
              ./scripts/retailer-certs.sh
      restartPolicy: Never
