apiVersion: v1
kind: Service
metadata:
  name: ca-distributor
  labels:
    app: ca-distributor
spec:
  type: ClusterIP
  selector:
    app: ca-distributor
  ports:
    - protocol: TCP
      targetPort: 5054
      port: 5054