apiVersion: v1
kind: Service
metadata:
  name: ca-regulator
  labels:
    app: ca-regulator
spec:
  type: ClusterIP
  selector:
    app: ca-regulator
  ports:
    - protocol: TCP
      targetPort: 8054
      port: 8054