apiVersion: v1
kind: Service
metadata:
  name: ca-retailer
  labels:
    app: ca-retailer
spec:
  type: ClusterIP
  selector:
    app: ca-retailer
  ports:
    - protocol: TCP
      targetPort: 9054
      port: 9054