apiVersion: v1
kind: Service
metadata:
  name: ca-storage
  labels:
    app: ca-storage
spec:
  type: ClusterIP
  selector:
    app: ca-storage
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054